# Generated by Django 4.2.7 on 2025-04-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='lead_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
