# Generated by Django 4.2.7 on 2025-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_subscriber_lead_status_subscriber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='unique_code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
