# Generated by Django 4.2.7 on 2025-05-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_subscriber_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='AA', max_length=2)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
    ]
